"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { IconArrowRight, IconCalendar, IconChartBar, IconCurrencyDollar, IconLayoutGrid, IconLoader2, IconPackage, IconShoppingBag, IconTrendingUp, IconUsers } from "@tabler/icons-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Order = { id: string; created_at: string; customer_name?: string | null; total?: number | null; status?: string | null; order_type?: string | null; table_id?: number | null };
const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });
const terminalStatuses = new Set(["entregado", "cancelado", "delivered", "cancelled", "completed"]);
const isToday = (value: string) => { const date = new Date(value); const today = new Date(); return date.getFullYear() === today.getFullYear() && date.getMonth() === today.getMonth() && date.getDate() === today.getDate(); };
const orderLabel = (order: Order) => order.customer_name?.trim() || (order.table_id ? `Mesa ${order.table_id}` : order.order_type === "DELIVERY" ? "Pedido delivery" : "Pedido sin nombre");

export function DashboardHomeClient() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => { void (async () => { try { const res = await fetch("/api/orders/list?days=8", { credentials: "include" }); const payload = await res.json() as { data?: Order[]; error?: string }; if (!res.ok) throw new Error(payload.error ?? "No se pudieron cargar las ventas"); setOrders(payload.data ?? []); } catch (err) { setError(err instanceof Error ? err.message : "No se pudieron cargar las ventas"); } finally { setLoading(false); } })(); }, []);

  const summary = useMemo(() => { const todayOrders = orders.filter((o) => isToday(o.created_at) && !terminalStatuses.has((o.status ?? "").toLowerCase())); const sales = todayOrders.reduce((sum, o) => sum + Number(o.total ?? 0), 0); return { sales, count: todayOrders.length, active: orders.filter((o) => !terminalStatuses.has((o.status ?? "").toLowerCase())).length, average: todayOrders.length ? sales / todayOrders.length : 0 }; }, [orders]);
  const chartData = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); const next = new Date(date); next.setDate(next.getDate() + 1); const ventas = orders.filter((o) => { const created = new Date(o.created_at); return created >= date && created < next && !terminalStatuses.has((o.status ?? "").toLowerCase()); }).reduce((sum, o) => sum + Number(o.total ?? 0), 0); return { label: date.toLocaleDateString("es-AR", { weekday: "short" }).replace(".", ""), ventas }; }), [orders]);
  const stats = [
    { label: "Ventas de hoy", value: money.format(summary.sales), detail: `${summary.count} pedidos registrados`, icon: IconCurrencyDollar, accent: "text-emerald-700 bg-emerald-50" },
    { label: "Ticket promedio", value: money.format(summary.average), detail: "Promedio de la jornada", icon: IconTrendingUp, accent: "text-sky-700 bg-sky-50" },
    { label: "Pedidos activos", value: String(summary.active), detail: "En salón, retiro o delivery", icon: IconShoppingBag, accent: "text-violet-700 bg-violet-50" },
    { label: "Operación", value: "Abierta", detail: "Gestioná mesas y cobros", icon: IconLayoutGrid, accent: "text-amber-700 bg-amber-50" },
  ];

  return <div className="space-y-6 pb-6">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-[#3d6b52]">Centro de control</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-gray-950 md:text-3xl">Buen día, equipo Bloom</h1><p className="mt-1 text-sm text-gray-500">Así está funcionando el local hoy.</p></div><div className="flex items-center gap-2 text-sm text-gray-500"><IconCalendar size={17} /> {new Date().toLocaleDateString("es-AR", { weekday: "long", day: "numeric", month: "long" })}</div></section>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">No fue posible actualizar las métricas: {error}</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, detail, icon: Icon, accent }) => <div key={label} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><p className="text-sm font-medium text-gray-500">{label}</p><span className={`grid h-9 w-9 place-items-center rounded-lg ${accent}`}><Icon size={19} /></span></div>{loading ? <IconLoader2 className="mt-5 animate-spin text-gray-400" size={23} /> : <p className="mt-5 text-2xl font-semibold tracking-tight text-gray-950">{value}</p>}<p className="mt-1 text-xs text-gray-500">{detail}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-5"><div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm xl:col-span-3"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-semibold text-gray-900">Ventas de la semana</h2><p className="mt-1 text-sm text-gray-500">Ingresos diarios de los últimos 7 días.</p></div><IconChartBar className="text-gray-400" size={20} /></div><div className="h-64">{loading ? <div className="grid h-full place-items-center"><IconLoader2 className="animate-spin text-gray-400" /></div> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 10, right: 0, left: -15, bottom: 0 }}><defs><linearGradient id="salesFill" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#3d6b52" stopOpacity={0.25}/><stop offset="95%" stopColor="#3d6b52" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "#737373", fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} width={46} tick={{ fill: "#a3a3a3", fontSize: 11 }} tickFormatter={(value) => `$${Math.round(value / 1000)}k`} /><Tooltip formatter={(value) => money.format(Number(value))} labelStyle={{ color: "#404040" }} contentStyle={{ borderRadius: 8, border: "1px solid #e5e5e5" }} /><Area type="monotone" dataKey="ventas" stroke="#3d6b52" strokeWidth={2.5} fill="url(#salesFill)" /></AreaChart></ResponsiveContainer>}</div></div>
      <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-gray-900">Pedidos recientes</h2><p className="mt-1 text-sm text-gray-500">Últimas operaciones registradas.</p></div><Link href="/dashboard/orders" className="text-sm font-medium text-[#3d6b52] hover:underline">Ver todos</Link></div><div className="mt-4 divide-y divide-gray-100">{loading ? <div className="grid h-44 place-items-center"><IconLoader2 className="animate-spin text-gray-400" /></div> : orders.length === 0 ? <p className="py-10 text-center text-sm text-gray-500">Todavía no hay pedidos para mostrar.</p> : orders.slice(0, 5).map((order) => <Link href="/dashboard/orders" key={order.id} className="flex items-center gap-3 py-3 transition hover:bg-gray-50"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-gray-100 text-xs font-semibold text-gray-600">{orderLabel(order).slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-gray-800">{orderLabel(order)}</span><span className="block text-xs text-gray-500">{new Date(order.created_at).toLocaleTimeString("es-AR", { hour: "2-digit", minute: "2-digit" })} · {order.order_type ?? "Local"}</span></span><span className="text-sm font-semibold text-gray-900">{money.format(Number(order.total ?? 0))}</span></Link>)}</div></div></section>
    <section className="grid gap-4 md:grid-cols-3"><QuickLink href="/dashboard/tables" icon={IconLayoutGrid} title="Administrar mesas" description="Abrí mesas, cargá consumos y cobrá." /><QuickLink href="/dashboard/compras-y-stock" icon={IconPackage} title="Compras y stock" description="Revisá insumos, movimientos y alertas." /><QuickLink href="/dashboard/clientes" icon={IconUsers} title="Clientes" description="Consultá saldos, pedidos e historial." /></section>
  </div>;
}

function QuickLink({ href, icon: Icon, title, description }: { href: string; icon: typeof IconLayoutGrid; title: string; description: string }) { return <Link href={href} className="group flex items-center gap-4 rounded-xl border border-gray-200 bg-white p-5 shadow-sm transition hover:border-[#a8c9b8] hover:shadow-md"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[#eef4f0] text-[#2d4a3e]"><Icon size={20} /></span><span className="min-w-0 flex-1"><span className="block font-medium text-gray-900">{title}</span><span className="mt-0.5 block text-sm text-gray-500">{description}</span></span><IconArrowRight size={18} className="text-gray-400 transition group-hover:translate-x-1 group-hover:text-[#2d4a3e]" /></Link>; }
