/**
 * Servicios de Vida de Perros (veterinaria + peluquería canina).
 *
 * Precios: `null` hasta que la dueña los defina → se muestra "Consultar".
 * Duraciones y franjas: valores operativos iniciales, editables desde
 * /veterinaria/admin/servicios.
 */
import type { Service, TimeRange, Weekday } from "../types";

const WEEKDAYS: Weekday[] = [1, 2, 3, 4, 5];
const WEEK_AND_SAT: Weekday[] = [1, 2, 3, 4, 5, 6];
const MORNING_AFTERNOON: TimeRange[] = [
  { from: "09:00", to: "13:00" },
  { from: "16:00", to: "20:00" },
];

export const SEED_SERVICES: Service[] = [
  {
    id: "consulta",
    slug: "consulta-veterinaria",
    kind: "veterinaria",
    name: "Consulta veterinaria",
    description: "Control general, vacunas, desparasitación y consultas clínicas con profesionales.",
    icon: "Stethoscope",
    durationMin: 30,
    price: null,
    days: WEEK_AND_SAT,
    hours: MORNING_AFTERNOON,
    capacity: 1,
    species: ["perro", "gato", "conejo", "ave", "pequenos"],
    visible: true,
    order: 1,
  },
  {
    id: "bano",
    slug: "bano",
    kind: "bano",
    name: "Baño",
    description: "Baño completo con productos adecuados para cada tipo de pelo y piel, secado y perfume.",
    icon: "ShowerHead",
    durationMin: 60,
    price: null,
    priceNote: "Según tamaño y tipo de pelo",
    days: WEEK_AND_SAT,
    hours: MORNING_AFTERNOON,
    capacity: 1,
    species: ["perro", "gato"],
    visible: true,
    order: 2,
    repeatEveryDays: 30,
  },
  {
    id: "peluqueria",
    slug: "peluqueria-canina",
    kind: "peluqueria",
    name: "Peluquería canina",
    description: "Baño y corte según raza o a gusto, con terminación prolija y cuidado del bienestar.",
    icon: "Scissors",
    durationMin: 90,
    price: null,
    priceNote: "Según tamaño, raza y estado del manto",
    days: WEEK_AND_SAT,
    hours: MORNING_AFTERNOON,
    capacity: 1,
    species: ["perro"],
    visible: true,
    order: 3,
    repeatEveryDays: 45,
  },
  {
    id: "unas",
    slug: "corte-de-unas",
    kind: "unas",
    name: "Corte de uñas",
    description: "Corte y limado de uñas de forma segura y tranquila.",
    icon: "Hand",
    durationMin: 15,
    price: null,
    days: WEEK_AND_SAT,
    hours: MORNING_AFTERNOON,
    capacity: 1,
    species: ["perro", "gato", "conejo", "ave", "pequenos"],
    visible: true,
    order: 4,
    repeatEveryDays: 30,
  },
  {
    id: "deslanado",
    slug: "deslanado",
    kind: "deslanado",
    name: "Deslanado",
    description: "Retiro del subpelo muerto para razas de doble manto. Ideal en cambios de estación.",
    icon: "Wind",
    durationMin: 90,
    price: null,
    priceNote: "Según tamaño y cantidad de subpelo",
    days: WEEKDAYS,
    hours: MORNING_AFTERNOON,
    capacity: 1,
    species: ["perro", "gato"],
    visible: true,
    order: 5,
    repeatEveryDays: 90,
  },
  {
    id: "higiene",
    slug: "higiene",
    kind: "higiene",
    name: "Higiene",
    description: "Limpieza de oídos, zona de ojos, almohadillas y zonas sanitarias.",
    icon: "Sparkles",
    durationMin: 30,
    price: null,
    days: WEEK_AND_SAT,
    hours: MORNING_AFTERNOON,
    capacity: 1,
    species: ["perro", "gato"],
    visible: true,
    order: 6,
    repeatEveryDays: 30,
  },
];
